### ISSUE TITLE
Compilation problem or r54

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jaraco/pyevent#16]
```
Hi, just tried to compile on my debian lenny with both gcc 4.3 and 4.1 and
receive an error:


michele:/home/devel/pyevent-read-only$ make
DISTUTILS_USE_SDK=1 MSSdk=1 python2.5 setup.py build
found system libevent for linux2
running build
running build_ext
building 'event' extension
/usr/bin/gcc-4.1 -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall
-Wstrict-prototypes -fPIC -I/usr/include/python2.5 -c event.c -o
build/temp.linux-i686-2.5/event.o
In file included from event.c:33:
/usr/include/evhttp.h:111: error: expected specifier-qualifier-list before
‘TAILQ_ENTRY’
event.c: In function ‘__pyx_f_5event_11bufferevent_read’:
event.c:1967: warning: pointer targets in passing argument 1 of
‘PyString_FromStringAndSize’ differ in signedness
event.c: In function ‘__pyx_f_5event_11bufferevent_write’:
event.c:2010: warning: passing argument 2 of ‘PyObject_AsCharBuffer’ from
incompatible pointer type
event.c: In function ‘__pyx_f_5event_dns_resolve_reverse’:
event.c:2494: warning: passing argument 1 of ‘evdns_resolve_reverse’ from
incompatible pointer type
event.c: In function ‘__pyx_f_5event_dns_resolve_reverse_ipv6’:
event.c:2566: warning: passing argument 1 of ‘evdns_resolve_reverse’ from
incompatible pointer type
event.c: In function ‘__pyx_f_5event_16__start_response___call__’:
event.c:2781: error: ‘struct evhttp_request’ has no member named
‘output_headers’
event.c: In function ‘__pyx_f_5event_12__wsgi_input_read’:
event.c:2945: warning: pointer targets in passing argument 1 of
‘PyString_FromStringAndSize’ differ in signedness
event.c: In function ‘__pyx_f_5event___path_handler’:
event.c:3079: error: ‘struct evhttp_request’ has no member named 
‘input_buffer’
event.c:3103: error: ‘struct evhttp_request’ has no member named ‘type’
event.c:3107: error: ‘struct evhttp_request’ has no member named ‘uri’
event.c:3112: error: ‘struct evhttp_request’ has no member named
‘input_headers’
event.c:3119: error: ‘struct evhttp_request’ has no member named
‘input_headers’
event.c:3126: error: ‘struct evhttp_request’ has no member named
‘input_headers’
event.c:3136: error: ‘struct evhttp_request’ has no member named ‘major’
event.c:3137: error: ‘struct evhttp_request’ has no member named ‘minor’
event.c:3147: error: ‘struct evhttp_request’ has no member named 
‘remote_host’
event.c:3150: error: ‘struct evhttp_request’ has no member named 
‘remote_host’
event.c:3153: error: ‘struct evhttp_request’ has no member named 
‘remote_port’
error: command '/usr/bin/gcc-4.1' failed with exit status 1
make: *** [all] Error 1

r53 works well.

```

Original issue reported on code.google.com by `michele....@gmail.com` on 23 Dec 2008 at 4:04
